### ISSUE TITLE
[PE-D][Tester B] PDF Table of Contents not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-4/tp#104]
Table of Contents links don't work in PDF.

![image.png](https://raw.githubusercontent.com/blaukc/ped/main/files/38bd312f-be8f-4753-90f3-01f1f9b3737e.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: blaukc/ped#2

**Comment by SimKianSeng** [comment]
duplicate of #140
