### ISSUE TITLE
[PE-D][Tester B] export command has some data in double quotes

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-4/tp#111]
![image.png](https://raw.githubusercontent.com/blaukc/ped/main/files/2962ba16-4334-4c1e-9f1c-7e7fe1206f4c.png)

Some dates and tags are in "double quotes", if I'm trying to export this data for use elsewhere this may be a hindrance.

Behavior differs from normal expectations

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: blaukc/ped#6

**Comment by SimKianSeng** [comment]
Try fixing functional code?
Perhaps state in UG?
