### ISSUE TITLE
[PE-D][Tester B] Unable to exit the command history without choosing one of the previous commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-4/tp#118]
When accessing command history, I am unable to exit it. If i press ESC a normal command history like in chrome's search bar would remove the suggestions, but this app chooses it 
instead 

Behavior differs from normal expectations

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: blaukc/ped#10

**Comment by SimKianSeng** [comment]
Fix in UG
