### ISSUE TITLE
[PE-D][Tester B] Odd command output from removeassign

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F10-4/tp#122]
![image.png](https://raw.githubusercontent.com/blaukc/ped/main/files/da7b2fd1-c50e-4498-9e8b-7dc06d1183e2.png)

Says "Assignment removed : Roy Balakrishnan assigned to aa aa on 03/05/2024", the part after the colon sounds like its from the assign command

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: blaukc/ped#11

**Comment by Benson15912** [comment]
Not sure how to reproduce this bug, will close this
