### ISSUE TITLE
[PE-D][Tester C] UI bug when adding a very long tag

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-4/tp#149]
## Issue:
- Entering a very long tag results in tag that cuts off other columns.
- Enter command below into input box:
```
edit 1 t/testtttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttttesttttttttttttttttttttt
```

## Output:
![image.png](https://raw.githubusercontent.com/guanquann/ped/main/files/0a41e9c6-f10a-48a5-b46d-38f4249dc473.png)

## Solution:
- Consider wrapping the tags around, or use ellipsis

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: guanquann/ped#10

**Comment by SimKianSeng** [comment]
Truncate our tag and also mention it in the UG
