### ISSUE TITLE
[PE-D][Tester A] Issue with UG on adding a person

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F10-4/tp#162]
- Issue:
At present, the app does not accept duplicate names. As shown in the following screenshot, there is already one person called "Zhang Wei" in the list. If there is another person also called "Zhang Wei", even though he/she has the different phone number and email address from the first "Zhang Wei", the app still doesn't accept him/her. The "adding aperson: add" part in UG also does not provide enough information on how to deal with the situation where two or more people have the same name.

- Suggestion:
Maybe you could add a line of instruction on how to deal with duplicate names in UG. You may consider this way "If you want add a person whose name is already in the list, you can add a number at the end of the person's name, e.g., the name "Zhang Wei" is already in the list, if you want to add another person whose name is also "Zhang Wei", you can input it as "add n/Zhang Wei 2 p/..."

![image.png](https://raw.githubusercontent.com/Morninggloryyy/ped/main/files/3eb7be72-601a-472a-9274-64910dbc7c16.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Morninggloryyy/ped#6

**Comment by YowSiaoKang** [comment]
Will specify in UG on what is considered duplication. However this feature of allowing duplicate name should be in planned enhancement
